// Build plan P9 — fictional demo dataset for the /recq candidate flow
// (scripts/seed-recq-demo.mjs). Every account lives on a non-routable .demo
// domain, so no real inbox ever receives these emails, and `--reset` can
// find and remove exactly this set.

import {
  DEMO_ACCOUNTS,
  DEMO_AGENCY_NAME,
  DEMO_AGENCY_SLUG,
  DEMO_AGENCY_B_NAME,
  DEMO_AGENCY_B_SLUG,
  DEMO_COMPANY_NAME,
} from '../../src/shared/constants/demo.js';

// recruitiq.demo = the previous (pre-P9) demo set, superseded by this one —
// --reset removes it too so a demo database ends up with a single demo set.
export const RECQ_DEMO_DOMAINS = ['platform.demo', 'nexora.demo', 'brightline.demo', 'finlytics.demo', 'mail.demo', 'recruitiq.demo'];

// The accounts shown on /live-demo (src/shared/constants/demo.js).
const byKey = Object.fromEntries(DEMO_ACCOUNTS.map((a) => [a.key, { email: a.email, name: a.fullName }]));
export const ACCOUNTS = {
  admin: byKey.admin,
  owner: byKey.agency,
  recruiter: byKey.recruiter,
  hr: byKey.hr,
  agencyB: byKey.agencyB,
};

export const AGENCY = {
  name: DEMO_AGENCY_NAME,
  slug: DEMO_AGENCY_SLUG,
  profile: {
    industry: 'Technology recruitment',
    size: '51-200',
    location: 'Pune, India',
    website: 'https://nexora.example.com',
    description:
      'Nexora Talent Partners hires engineering and data talent for fast-growing product companies across India.',
  },
};

export const AGENCY_B = { name: DEMO_AGENCY_B_NAME, slug: DEMO_AGENCY_B_SLUG };

export const CLIENT = { name: DEMO_COMPANY_NAME, industry: 'FinTech', website: 'https://finlytics.example.com', department: 'Engineering' };

const H = 3600 * 1000;
const D = 24 * H;

// interview windows are relative to "now" when the seed runs
export const JOBS = [
  {
    key: 'mern',
    title: 'MERN Stack Developer',
    description:
      'Finlytics is building a modern lending platform. As a MERN Stack Developer you will design and ship features end to end with MongoDB, Express.js, React and Node.js, build secure REST APIs, and work closely with product and design.\n\nWhat you will do:\n- Build React interfaces with clean, reusable components and Redux state management\n- Design and secure Node.js / Express REST APIs (JWT auth, validation, rate limiting)\n- Model data in MongoDB and keep queries fast\n- Write tests and review code\n\nYou have 2–5 years of hands-on MERN experience and a B.E./B.Tech in Computer Science or IT.',
    requiredSkills: ['MongoDB', 'Express.js', 'React', 'Node.js', 'JavaScript', 'REST APIs'],
    preferredSkills: ['TypeScript', 'Redux', 'AWS', 'Jest'],
    educationRequirements: ['B.E./B.Tech in Computer Science or IT'],
    minimumExperience: 2,
    maximumExperience: 5,
    location: 'Pune',
    workMode: 'Hybrid',
    employmentType: 'FULL_TIME',
    jobLevel: 'Mid',
    openings: 3,
    salaryRange: '₹10–16 LPA',
    minAcceptableScore: 65,
    finalThreshold: 70,
    client: true,
    window: { start: -8 * D, end: 14 * D },
    config: {
      aiName: 'Ananya',
      aiTitle: 'Senior Technical Recruiter',
      questionCount: 6,
      answerTimeSeconds: 90,
      voiceGender: 'FEMALE',
      difficultyStrategy: 'ADAPTIVE',
      customQuestions: [
        'Walk me through a MERN application you built end to end. What exactly was your part?',
        'How would you secure a Node.js REST API that handles customer financial data?',
      ],
      interviewInstructions:
        'Focus on hands-on MERN delivery. Ask for concrete examples from projects the candidate actually built, including trade-offs they made.',
      evaluationInstructions:
        'Explains JWT/session authentication correctly\nShows solid React state management (hooks, Redux or Context)\nCan reason about MongoDB schema design and indexes\nCommunicates clearly and structures answers',
      focusSkills: ['React', 'Node.js', 'MongoDB', 'API security'],
    },
  },
  {
    key: 'backend',
    title: 'Backend Node.js Developer',
    description:
      'Join the platform team that runs payment and ledger services. You will build reliable Node.js microservices on Express.js and PostgreSQL, containerise them with Docker, and own performance and observability.\n\nWhat you will do:\n- Design REST APIs and background workers in Node.js\n- Model relational data in PostgreSQL and tune slow queries\n- Add caching with Redis and messaging with Kafka where it helps\n- Ship with Docker and CI/CD, and keep services observable\n\nYou have 3–6 years of backend experience with Node.js.',
    requiredSkills: ['Node.js', 'Express.js', 'PostgreSQL', 'REST APIs', 'Docker'],
    preferredSkills: ['Redis', 'Kafka', 'AWS', 'Microservices'],
    educationRequirements: ['B.E./B.Tech or MCA'],
    minimumExperience: 3,
    maximumExperience: 6,
    location: 'Bengaluru',
    workMode: 'On-site',
    employmentType: 'FULL_TIME',
    jobLevel: 'Senior',
    openings: 2,
    salaryRange: '₹16–24 LPA',
    minAcceptableScore: 65,
    finalThreshold: 70,
    client: true,
    window: null,
    config: {
      aiName: 'Vikram',
      aiTitle: 'Engineering Manager',
      questionCount: 6,
      answerTimeSeconds: 120,
      voiceGender: 'MALE',
      difficultyStrategy: 'ADAPTIVE',
      customQuestions: ['How would you design rate limiting for a public payments API?'],
      interviewInstructions: 'Probe system design, database modelling and production debugging experience.',
      evaluationInstructions:
        'Designs sensible relational schemas and indexes\nUnderstands scaling (caching, queues, horizontal scaling)\nHas real production debugging experience',
      focusSkills: ['Node.js', 'PostgreSQL', 'System design'],
    },
  },
  {
    key: 'react',
    title: 'React Developer',
    description:
      'A remote contract role building customer-facing dashboards. You will turn Figma designs into fast, accessible React interfaces with Tailwind CSS and integrate them with REST APIs.\n\nYou have 1–3 years of React experience, strong JavaScript, HTML and CSS, and care about performance and accessibility.',
    requiredSkills: ['React', 'JavaScript', 'HTML', 'CSS', 'Tailwind CSS'],
    preferredSkills: ['TypeScript', 'Next.js', 'Testing Library'],
    educationRequirements: ['Any graduate degree'],
    minimumExperience: 1,
    maximumExperience: 3,
    location: 'Remote (India)',
    workMode: 'Remote',
    employmentType: 'CONTRACT',
    jobLevel: 'Junior',
    openings: 2,
    salaryRange: '₹60–90k / month',
    minAcceptableScore: 60,
    finalThreshold: null, // recruiter decides manually
    client: false,
    window: { start: -8 * D, end: 7 * D },
    config: {
      aiName: 'Priya',
      aiTitle: 'Virtual HR',
      questionCount: 5,
      answerTimeSeconds: 60,
      voiceGender: 'FEMALE',
      difficultyStrategy: 'FIXED',
      customQuestions: ['How do you make a React page fast and accessible?'],
      interviewInstructions: 'Keep it friendly and practical; this is a junior-to-mid role.',
      evaluationInstructions: 'Understands React hooks and component design\nKnows basic accessibility and performance practices',
      focusSkills: ['React', 'CSS'],
    },
  },
  {
    key: 'aiml',
    title: 'AI/ML Engineer',
    description:
      'Build and deploy machine learning models for credit risk and document understanding. You will train models in Python and PyTorch, build NLP pipelines, and take models to production with MLOps best practices.\n\nYou have 2–5 years of ML experience and an M.Tech/B.Tech in CS, Data Science or a related field.',
    requiredSkills: ['Python', 'PyTorch', 'Machine Learning', 'NLP', 'SQL'],
    preferredSkills: ['LLMs', 'MLOps', 'Docker', 'AWS SageMaker'],
    educationRequirements: ['M.Tech/B.Tech in CS, Data Science or related'],
    minimumExperience: 2,
    maximumExperience: 5,
    location: 'Hyderabad',
    workMode: 'Hybrid',
    employmentType: 'FULL_TIME',
    jobLevel: 'Mid',
    openings: 1,
    salaryRange: '₹18–28 LPA',
    minAcceptableScore: 70,
    finalThreshold: 75,
    client: true,
    window: { start: -8 * D, end: 10 * D },
    config: {
      aiName: 'Kavya',
      aiTitle: 'ML Lead',
      questionCount: 7,
      answerTimeSeconds: 120,
      voiceGender: 'FEMALE',
      difficultyStrategy: 'ADAPTIVE',
      customQuestions: ['Describe a model you took from experiment to production. How did you monitor it?'],
      interviewInstructions: 'Check depth in model evaluation, NLP and production ML.',
      evaluationInstructions: 'Chooses appropriate evaluation metrics\nUnderstands overfitting and data leakage\nHas shipped a model to production',
      focusSkills: ['PyTorch', 'NLP', 'MLOps'],
    },
  },
  {
    key: 'analyst',
    title: 'Data Analyst Intern',
    description:
      'A 6-month paid internship in our analytics team. You will clean data with SQL and Python, build Power BI dashboards and present insights to business teams.\n\nFinal-year students and fresh graduates are welcome.',
    requiredSkills: ['SQL', 'Excel', 'Python', 'Power BI'],
    preferredSkills: ['Statistics', 'Tableau'],
    educationRequirements: ['Pursuing or completed graduation'],
    minimumExperience: 0,
    maximumExperience: 1,
    location: 'Ahmedabad',
    workMode: 'On-site',
    employmentType: 'INTERNSHIP',
    jobLevel: 'Junior',
    openings: 4,
    salaryRange: '₹25k / month stipend',
    minAcceptableScore: 55,
    finalThreshold: null,
    client: false,
    // Opens in the future — demonstrates "your interview is not available yet".
    window: { start: 3 * D, end: 10 * D },
    config: {
      aiName: 'Priya',
      aiTitle: 'Campus Recruiter',
      questionCount: 4,
      answerTimeSeconds: 60,
      voiceGender: 'FEMALE',
      difficultyStrategy: 'FIXED',
      customQuestions: [],
      focusSkills: ['SQL', 'Excel'],
    },
  },
];

export const CLOSED_JOBS = [
  { key: 'php', title: 'PHP Laravel Developer', requiredSkills: ['PHP', 'Laravel', 'MySQL'], location: 'Pune' },
  { key: 'qa', title: 'QA Automation Engineer', requiredSkills: ['Selenium', 'Java', 'TestNG'], location: 'Pune' },
];

export const AGENCY_B_JOBS = [
  {
    key: 'java',
    title: 'Java Spring Boot Developer',
    description:
      'Build enterprise services with Java 17 and Spring Boot, design REST APIs and work with MySQL and Kafka for a logistics client.',
    requiredSkills: ['Java', 'Spring Boot', 'MySQL', 'REST APIs'],
    minimumExperience: 2,
    location: 'Chennai',
    minAcceptableScore: 60,
  },
  {
    key: 'devops',
    title: 'DevOps Engineer',
    description: 'Own CI/CD pipelines, Kubernetes clusters and AWS infrastructure as code with Terraform for a retail client.',
    requiredSkills: ['AWS', 'Kubernetes', 'Terraform', 'CI/CD'],
    minimumExperience: 2,
    location: 'Gurugram',
    minAcceptableScore: 60,
  },
];

// ─── Candidates ───
// `apply`: job keys to apply to; `discover: true` uses the agency-wide resume
// discovery (Option B), otherwise the job page (Option A).
// `interview`: { job, level } runs the real AI interview with answers in
// that quality level; `after`: post-interview action.
export const CANDIDATES = [
  {
    name: 'Priya Sharma',
    email: 'priya.sharma@mail.demo',
    discover: true,
    apply: ['mern', 'react'],
    interview: { job: 'mern', level: 'strong' },
    after: 'submit',
    lines: (n, e) => [
      n,
      `${e}  |  +91 98220 41157  |  Pune, Maharashtra`,
      'linkedin.com/in/priya-sharma-dev  |  github.com/priyasharma',
      '',
      'PROFESSIONAL SUMMARY',
      'Full-stack MERN developer with 4 years of experience building secure, high-traffic web applications for FinTech and e-commerce products.',
      '',
      'TECHNICAL SKILLS',
      'MongoDB, Express.js, React, Node.js, JavaScript (ES2022), TypeScript, Redux Toolkit, REST APIs, JWT, Jest, Docker, AWS (EC2, S3), Git',
      '',
      'EXPERIENCE',
      'Software Engineer II — PayNest Technologies, Pune (Jun 2022 – Present)',
      '- Built the loan-application portal in React + TypeScript and Redux Toolkit used by 120k customers a month.',
      '- Designed Node.js/Express REST APIs with JWT refresh tokens, role-based access and rate limiting.',
      '- Reduced MongoDB query time by 60% with compound indexes and aggregation pipelines.',
      'Software Engineer — CartCraft Labs, Pune (Jul 2020 – May 2022)',
      '- Developed MERN-stack checkout and order-tracking features; raised test coverage to 80% with Jest.',
      '',
      'EDUCATION',
      'B.E. Computer Engineering — Savitribai Phule Pune University, 2020 (CGPA 8.6)',
      '',
      'CERTIFICATIONS',
      'AWS Certified Developer – Associate (2023)',
    ],
  },
  {
    name: 'Arjun Verma',
    email: 'arjun.verma@mail.demo',
    apply: ['backend'],
    interview: { job: 'backend', level: 'strong' },
    after: null, // QUALIFIED by the final score
    lines: (n, e) => [
      n,
      `${e}  |  +91 99001 22345  |  Bengaluru, Karnataka`,
      '',
      'SUMMARY',
      'Backend engineer with 5 years of experience building payment and ledger microservices in Node.js and PostgreSQL.',
      '',
      'SKILLS',
      'Node.js, Express.js, TypeScript, PostgreSQL, Redis, Kafka, Docker, Kubernetes, REST APIs, Microservices, AWS, CI/CD',
      '',
      'EXPERIENCE',
      'Senior Backend Engineer — LedgerLoop, Bengaluru (2022 – Present)',
      '- Owns the ledger service processing 2M transactions a day (Node.js, PostgreSQL, Kafka).',
      '- Introduced Redis caching and idempotency keys; p95 latency dropped from 480 ms to 120 ms.',
      'Backend Engineer — Swiftcart, Bengaluru (2019 – 2022)',
      '- Built order and inventory REST APIs in Express.js; containerised services with Docker.',
      '',
      'EDUCATION',
      'B.Tech Information Technology — VIT Vellore, 2019',
    ],
  },
  {
    name: 'Sneha Kulkarni',
    email: 'sneha.kulkarni@mail.demo',
    apply: ['react'],
    interview: { job: 'react', level: 'average' },
    after: null, // stays "Interview completed" — recruiter review
    lines: (n, e) => [
      n,
      `${e}  |  +91 97650 33218  |  Nagpur, Maharashtra`,
      '',
      'SUMMARY',
      'Frontend developer with 2 years of experience building React screens for an internal HR tool.',
      '',
      'SKILLS',
      'React, JavaScript, HTML, CSS, Bootstrap, Tailwind CSS, Git, REST APIs',
      '',
      'EXPERIENCE',
      'Frontend Developer — Orbit HR Solutions, Nagpur (2023 – Present)',
      '- Built React forms and tables for leave and payroll modules.',
      '- Converted Bootstrap pages to Tailwind CSS.',
      '',
      'EDUCATION',
      'B.Sc. Computer Science — RTM Nagpur University, 2022',
    ],
  },
  {
    name: 'Karan Malhotra',
    email: 'karan.malhotra@mail.demo',
    apply: ['backend'],
    interview: { job: 'backend', level: 'weak' },
    after: 'reject',
    lines: (n, e) => [
      n,
      `${e}  |  +91 98110 76543  |  Noida, Uttar Pradesh`,
      '',
      'SUMMARY',
      'Backend developer with 3 years of experience in Node.js services and PostgreSQL databases.',
      '',
      'SKILLS',
      'Node.js, Express.js, PostgreSQL, MySQL, REST APIs, Docker, Redis, Git',
      '',
      'EXPERIENCE',
      'Backend Developer — TechNova Services, Noida (2022 – Present)',
      '- Maintained Express.js REST APIs and PostgreSQL stored procedures for a CRM product.',
      'Junior Developer — Webline Infosoft, Noida (2021 – 2022)',
      '- Fixed bugs in Node.js and MySQL based admin panels; wrote Dockerfiles for local setup.',
      '',
      'EDUCATION',
      'MCA — Amity University, 2021',
    ],
  },
  {
    name: 'Ananya Iyer',
    email: 'ananya.iyer@mail.demo',
    apply: ['aiml'],
    interview: null,
    lines: (n, e) => [
      n,
      `${e}  |  +91 90030 55887  |  Hyderabad, Telangana`,
      '',
      'SUMMARY',
      'Machine learning engineer with 3 years of experience in NLP and document AI, from research to production.',
      '',
      'SKILLS',
      'Python, PyTorch, Machine Learning, NLP, Transformers, LLMs, SQL, MLOps, MLflow, Docker, AWS SageMaker',
      '',
      'EXPERIENCE',
      'ML Engineer — DocuMind AI, Hyderabad (2022 – Present)',
      '- Fine-tuned transformer models for invoice field extraction (F1 0.81 → 0.93).',
      '- Built an MLflow + SageMaker pipeline with drift monitoring for production models.',
      'Data Scientist — Insightly Analytics (2021 – 2022)',
      '- Built churn models in scikit-learn and PyTorch.',
      '',
      'EDUCATION',
      'M.Tech Artificial Intelligence — IIIT Hyderabad, 2021',
    ],
  },
  {
    name: 'Vikram Joshi',
    email: 'vikram.joshi@mail.demo',
    apply: ['mern'],
    interview: null,
    lines: (n, e) => [
      n,
      `${e}  |  +91 98500 11002  |  Mumbai, Maharashtra`,
      '',
      'SUMMARY',
      'Full-stack developer with 2.5 years of experience on MERN-stack projects.',
      '',
      'SKILLS',
      'MongoDB, Express.js, React, Node.js, JavaScript, REST APIs, Git, Postman',
      '',
      'EXPERIENCE',
      'Full Stack Developer — Brandwise Digital, Mumbai (2023 – Present)',
      '- Built React admin dashboards and Express APIs for marketing clients.',
      'Intern — CodeCraft Studio (2022 – 2023)',
      '',
      'EDUCATION',
      'B.Tech Computer Science — University of Mumbai, 2022',
    ],
  },
  {
    name: 'Meera Nair',
    email: 'meera.nair@mail.demo',
    apply: ['react'],
    interview: null,
    lines: (n, e) => [
      n,
      `${e}  |  +91 94470 66512  |  Kochi, Kerala`,
      '',
      'SUMMARY',
      'Frontend engineer with 3 years of React and TypeScript experience, focused on accessibility and performance.',
      '',
      'SKILLS',
      'React, TypeScript, JavaScript, HTML, CSS, Tailwind CSS, Next.js, Testing Library, Web accessibility (WCAG)',
      '',
      'EXPERIENCE',
      'Frontend Engineer — Lumen Health, Kochi (2022 – Present)',
      '- Rebuilt the patient portal in Next.js; Lighthouse performance score 58 → 95.',
      '- Led WCAG 2.1 AA accessibility fixes across 40 screens.',
      '',
      'EDUCATION',
      'B.Tech Computer Science — CUSAT, 2021',
    ],
  },
  {
    name: 'Rohit Patil',
    email: 'rohit.patil@mail.demo',
    apply: ['analyst'],
    interview: null,
    lines: (n, e) => [
      n,
      `${e}  |  +91 99250 44871  |  Ahmedabad, Gujarat`,
      '',
      'SUMMARY',
      'Final-year B.Com (Computer Applications) student with strong SQL and Excel skills, looking for a data analyst internship.',
      '',
      'SKILLS',
      'SQL, Excel (Pivot tables, VLOOKUP), Python (Pandas), Power BI, Statistics',
      '',
      'PROJECTS',
      '- Sales dashboard in Power BI for a local retail chain (12 stores).',
      '- Analysed 50k rows of e-commerce orders with Pandas and SQL.',
      '',
      'EDUCATION',
      'B.Com (Computer Applications) — Gujarat University, expected 2026',
    ],
  },
  {
    name: 'Fatima Sheikh',
    email: 'fatima.sheikh@mail.demo',
    discover: true,
    apply: ['mern', 'backend'],
    interview: null,
    lines: (n, e) => [
      n,
      `${e}  |  +91 98190 27731  |  Pune, Maharashtra`,
      '',
      'SUMMARY',
      'Full-stack engineer with 4 years of experience across React frontends and Node.js/PostgreSQL backends.',
      '',
      'SKILLS',
      'React, Node.js, Express.js, MongoDB, PostgreSQL, Docker, REST APIs, Redis, JavaScript, TypeScript, AWS',
      '',
      'EXPERIENCE',
      'Full Stack Engineer — Quickserve Logistics, Pune (2021 – Present)',
      '- Built the dispatch dashboard (React) and route APIs (Node.js, PostgreSQL, Redis).',
      '- Containerised 9 services with Docker and set up GitHub Actions CI.',
      '',
      'EDUCATION',
      'B.E. Information Technology — Pune Institute of Computer Technology, 2021',
    ],
  },
  {
    name: 'Ishita Banerjee',
    email: 'ishita.banerjee@mail.demo',
    apply: ['react'],
    interview: null,
    lines: (n, e) => [
      n,
      `${e}  |  +91 98300 55129  |  Kolkata, West Bengal`,
      '',
      'SUMMARY',
      'Junior React developer with 1 year of experience and a strong portfolio of personal projects.',
      '',
      'SKILLS',
      'React, JavaScript, HTML, CSS, Tailwind CSS, Firebase, Git',
      '',
      'EXPERIENCE',
      'Junior Frontend Developer — Pixelport Studio, Kolkata (2025 – Present)',
      '',
      'EDUCATION',
      'B.Tech Computer Science — Heritage Institute of Technology, 2024',
    ],
  },
  {
    name: 'Rahul Deshmukh',
    email: 'rahul.deshmukh@mail.demo',
    apply: ['mern'],
    interview: null,
    lines: (n, e) => [
      n,
      `${e}  |  +91 97300 81244  |  Nashik, Maharashtra`,
      '',
      'SUMMARY',
      'MERN developer with 3 years of experience building SaaS dashboards.',
      '',
      'SKILLS',
      'MongoDB, Express.js, React, Node.js, Redux, JavaScript, REST APIs, Jest, AWS',
      '',
      'EXPERIENCE',
      'Software Developer — Cloudnest SaaS, Nashik (2022 – Present)',
      '- Built subscription billing UI in React/Redux and Node.js webhooks for payments.',
      '',
      'EDUCATION',
      'B.E. Computer Engineering — K.K. Wagh College of Engineering, 2022',
    ],
  },
];

// Applicants of the second agency (isolation demo).
export const CANDIDATES_B = [
  {
    name: 'Neha Gupta',
    email: 'neha.gupta@mail.demo',
    apply: ['java'],
    lines: (n, e) => [
      n,
      `${e}  |  +91 98840 13579  |  Chennai, Tamil Nadu`,
      '',
      'SUMMARY',
      'Java backend developer with 3 years of Spring Boot experience.',
      '',
      'SKILLS',
      'Java 17, Spring Boot, MySQL, REST APIs, Kafka, Docker, JUnit',
      '',
      'EXPERIENCE',
      'Software Engineer — Freightly, Chennai (2022 – Present)',
      '',
      'EDUCATION',
      'B.E. Computer Science — Anna University, 2022',
    ],
  },
  {
    name: 'Siddharth Menon',
    email: 'siddharth.menon@mail.demo',
    apply: ['devops'],
    lines: (n, e) => [
      n,
      `${e}  |  +91 98450 24680  |  Gurugram, Haryana`,
      '',
      'SUMMARY',
      'DevOps engineer with 4 years of experience on AWS, Kubernetes and Terraform.',
      '',
      'SKILLS',
      'AWS, Kubernetes, Terraform, Docker, Jenkins, GitHub Actions, CI/CD, Prometheus, Linux',
      '',
      'EXPERIENCE',
      'DevOps Engineer — Retailio Cloud, Gurugram (2021 – Present)',
      '',
      'EDUCATION',
      'B.Tech Electronics — NIT Kurukshetra, 2021',
    ],
  },
];

// Resumes for the LIVE part of the demo (written to demo-resumes/, never
// seeded): one strong multi-job resume and one weak resume.
export const LIVE_RESUMES = [
  {
    file: 'Kavya_Reddy_FullStack_Resume.docx',
    name: 'Kavya Reddy',
    email: 'kavya.reddy@mail.demo',
    lines: (n, e) => [
      n,
      `${e}  |  +91 98490 70123  |  Hyderabad, Telangana`,
      'linkedin.com/in/kavya-reddy  |  github.com/kavyareddy',
      '',
      'PROFESSIONAL SUMMARY',
      'Full-stack JavaScript engineer with 4 years of experience shipping React and Node.js products on MongoDB and PostgreSQL.',
      '',
      'TECHNICAL SKILLS',
      'React, Redux, TypeScript, JavaScript, Node.js, Express.js, MongoDB, PostgreSQL, REST APIs, JWT, Docker, Redis, Tailwind CSS, Jest, AWS',
      '',
      'EXPERIENCE',
      'Senior Software Engineer — Trailblaze Fintech, Hyderabad (2023 – Present)',
      '- Lead developer of the merchant dashboard (React, TypeScript, Redux Toolkit) used by 18k merchants.',
      '- Built Node.js/Express payment APIs with JWT auth, idempotency keys and PostgreSQL.',
      'Software Engineer — Bytewise Labs, Hyderabad (2021 – 2023)',
      '- Delivered MERN-stack features for a B2B marketplace; cut API latency 40% with Redis caching.',
      '',
      'EDUCATION',
      'B.Tech Computer Science — JNTU Hyderabad, 2021 (CGPA 8.9)',
    ],
  },
  {
    file: 'Aditya_Rao_Resume.docx',
    name: 'Aditya Rao',
    email: 'aditya.rao@mail.demo',
    lines: (n, e) => [
      n,
      `${e}  |  +91 90080 31415  |  Mysuru, Karnataka`,
      '',
      'SUMMARY',
      'Customer support executive with 3 years of experience in voice and chat support for a telecom provider.',
      '',
      'SKILLS',
      'Customer handling, complaint resolution, CRM tools (Zendesk), MS Office, Kannada, Hindi, English',
      '',
      'EXPERIENCE',
      'Customer Support Executive — Connectel BPO, Mysuru (2022 – Present)',
      '- Handled 80+ customer calls a day with a 92% satisfaction score.',
      '',
      'EDUCATION',
      'B.A. Economics — University of Mysore, 2021',
    ],
  },
];
