// Build plan P9 — extra fictional applicants for the /recq demo
// (scripts/seed-recq-demo.mjs seeds them by default; `--extra` adds only these
// to an existing demo set). They go through the real /recq flow (resume → AI
// match → email OTP → apply) and keep their interview pending, so every Nexora
// job has a fuller applicant list. Same .demo domain as the rest of the set.

export const CANDIDATES_EXTRA = [
  {
    name: 'Nikhil Bhosale',
    email: 'nikhil.bhosale@mail.demo',
    apply: ['mern'],
    lines: (n, e) => [
      n,
      `${e}  |  +91 98221 30456  |  Pune, Maharashtra`,
      '',
      'SUMMARY',
      'MERN developer with 3 years of experience building B2B SaaS dashboards and REST APIs.',
      '',
      'SKILLS',
      'MongoDB, Express.js, React, Node.js, JavaScript, TypeScript, Redux, REST APIs, Jest, Docker',
      '',
      'EXPERIENCE',
      'Software Engineer — Stackly SaaS, Pune (2022 – Present)',
      '- Built the analytics dashboard in React + Redux and the Node.js reporting API on MongoDB aggregations.',
      'Junior Developer — Codewave, Pune (2021 – 2022)',
      '',
      'EDUCATION',
      'B.E. Information Technology — MIT Pune, 2021',
    ],
  },
  {
    name: 'Pooja Iyengar',
    email: 'pooja.iyengar@mail.demo',
    apply: ['mern'],
    lines: (n, e) => [
      n,
      `${e}  |  +91 99860 42317  |  Bengaluru, Karnataka`,
      '',
      'SUMMARY',
      'Full-stack developer with 2 years of experience, mostly frontend React with some Node.js.',
      '',
      'SKILLS',
      'React, JavaScript, Node.js, Express.js, MongoDB, HTML, CSS, Git',
      '',
      'EXPERIENCE',
      'Associate Software Engineer — Brightminds Edtech, Bengaluru (2023 – Present)',
      '- Built course pages in React and Express endpoints for quizzes backed by MongoDB.',
      '',
      'EDUCATION',
      'B.Tech Computer Science — PES University, 2023',
    ],
  },
  {
    name: 'Amit Chauhan',
    email: 'amit.chauhan@mail.demo',
    apply: ['backend'],
    lines: (n, e) => [
      n,
      `${e}  |  +91 98100 55290  |  Gurugram, Haryana`,
      '',
      'SUMMARY',
      'Backend engineer with 4 years of experience in Node.js microservices, PostgreSQL and AWS.',
      '',
      'SKILLS',
      'Node.js, Express.js, TypeScript, PostgreSQL, Redis, Docker, Kubernetes, AWS, REST APIs, Microservices',
      '',
      'EXPERIENCE',
      'Senior Software Engineer — PayRoute, Gurugram (2022 – Present)',
      '- Built the settlement service in Node.js/PostgreSQL; added Redis caching and idempotent retries.',
      'Software Engineer — Zipkart Logistics, Gurugram (2021 – 2022)',
      '',
      'EDUCATION',
      'B.Tech Computer Science — Delhi Technological University, 2021',
    ],
  },
  {
    name: 'Divya Menon',
    email: 'divya.menon@mail.demo',
    apply: ['backend'],
    lines: (n, e) => [
      n,
      `${e}  |  +91 94477 63104  |  Thiruvananthapuram, Kerala`,
      '',
      'SUMMARY',
      'Backend developer with 3 years of experience in Node.js and relational databases for e-commerce clients.',
      '',
      'SKILLS',
      'Node.js, Express.js, PostgreSQL, MySQL, REST APIs, Docker, Git',
      '',
      'EXPERIENCE',
      'Backend Developer — Keralix Solutions, Thiruvananthapuram (2022 – Present)',
      '- Maintained order and payment APIs in Express.js; migrated reporting from MySQL to PostgreSQL.',
      '',
      'EDUCATION',
      'B.Tech Information Technology — College of Engineering Trivandrum, 2022',
    ],
  },
  {
    name: 'Sanya Kapoor',
    email: 'sanya.kapoor@mail.demo',
    apply: ['react'],
    lines: (n, e) => [
      n,
      `${e}  |  +91 98711 27840  |  New Delhi`,
      '',
      'SUMMARY',
      'Frontend developer with 2 years of React and Tailwind CSS experience on dashboards and marketing sites.',
      '',
      'SKILLS',
      'React, JavaScript, TypeScript, HTML, CSS, Tailwind CSS, Next.js, Figma',
      '',
      'EXPERIENCE',
      'Frontend Developer — Pixelcraft Agency, New Delhi (2024 – Present)',
      '- Built responsive React + Tailwind landing pages and an admin dashboard for six clients.',
      '',
      'EDUCATION',
      'B.Sc. Computer Science — University of Delhi, 2023',
    ],
  },
  {
    name: 'Harsh Vardhan',
    email: 'harsh.vardhan@mail.demo',
    apply: ['aiml'],
    lines: (n, e) => [
      n,
      `${e}  |  +91 90100 88213  |  Hyderabad, Telangana`,
      '',
      'SUMMARY',
      'Machine learning engineer with 2.5 years of experience in NLP and recommendation models.',
      '',
      'SKILLS',
      'Python, PyTorch, Machine Learning, NLP, Hugging Face Transformers, SQL, Pandas, Docker, MLflow',
      '',
      'EXPERIENCE',
      'ML Engineer — Vernacular AI Labs, Hyderabad (2023 – Present)',
      '- Fine-tuned multilingual BERT models for intent detection; built an MLflow-based training pipeline.',
      '',
      'EDUCATION',
      'B.Tech Computer Science (AI & ML) — IIIT Hyderabad, 2023',
    ],
  },
  {
    name: 'Riya Jain',
    email: 'riya.jain@mail.demo',
    apply: ['aiml'],
    lines: (n, e) => [
      n,
      `${e}  |  +91 97560 44102  |  Indore, Madhya Pradesh`,
      '',
      'SUMMARY',
      'Data scientist with 3 years of experience in machine learning, NLP basics and analytics.',
      '',
      'SKILLS',
      'Python, Machine Learning, scikit-learn, PyTorch, NLP, SQL, Pandas, Statistics, Tableau',
      '',
      'EXPERIENCE',
      'Data Scientist — Finsight Analytics, Indore (2022 – Present)',
      '- Built credit-risk scoring models with gradient boosting and a text classifier for support tickets.',
      '',
      'EDUCATION',
      'M.Tech Data Science — IIT Indore, 2022',
    ],
  },
  {
    name: 'Aakash Pandey',
    email: 'aakash.pandey@mail.demo',
    apply: ['analyst'],
    lines: (n, e) => [
      n,
      `${e}  |  +91 99780 21566  |  Ahmedabad, Gujarat`,
      '',
      'SUMMARY',
      'Final-year B.Tech student interested in data analytics, with SQL, Python and Power BI projects.',
      '',
      'SKILLS',
      'SQL, Excel, Python, Power BI, Pandas, Statistics',
      '',
      'PROJECTS',
      '- HR attrition analysis on 15k rows (Python, SQL) and a Power BI dashboard for a college fest.',
      '',
      'EDUCATION',
      'B.Tech Computer Engineering — Nirma University, expected 2026',
    ],
  },
  {
    name: 'Kritika Sharma',
    email: 'kritika.sharma@mail.demo',
    apply: ['analyst'],
    lines: (n, e) => [
      n,
      `${e}  |  +91 98250 77341  |  Vadodara, Gujarat`,
      '',
      'SUMMARY',
      'Commerce graduate moving into data analysis; strong Excel, learning SQL and Power BI.',
      '',
      'SKILLS',
      'Excel (advanced), SQL, Power BI, Python (basic), Statistics',
      '',
      'EXPERIENCE',
      'Accounts Assistant — Shree Traders, Vadodara (2024 – Present)',
      '- Built Excel and Power BI sales reports for the owners every month.',
      '',
      'EDUCATION',
      'B.Com — The Maharaja Sayajirao University of Baroda, 2024',
    ],
  },
];

// Applied this many days ago (for the realistic timeline step).
export const EXTRA_DAYS_AGO = {
  'nikhil.bhosale@mail.demo': 2,
  'pooja.iyengar@mail.demo': 1,
  'amit.chauhan@mail.demo': 3,
  'divya.menon@mail.demo': 2,
  'sanya.kapoor@mail.demo': 1,
  'harsh.vardhan@mail.demo': 2,
  'riya.jain@mail.demo': 1,
  'aakash.pandey@mail.demo': 1,
  'kritika.sharma@mail.demo': 0,
};
