-- AlterTable
ALTER TABLE "jobs" ADD COLUMN IF NOT EXISTS "workMode" TEXT NOT NULL DEFAULT 'On-site',
ADD COLUMN IF NOT EXISTS "openings" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN IF NOT EXISTS "jobLevel" TEXT NOT NULL DEFAULT 'Mid',
ADD COLUMN IF NOT EXISTS "noticePeriod" TEXT,
ADD COLUMN IF NOT EXISTS "languagesRequired" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN IF NOT EXISTS "certifications" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN IF NOT EXISTS "salaryRange" TEXT;
